### ISSUE TITLE
Calling getSystemTimeZone() results in a nullpointer exception

### ISSUE THREAD

**Issue by ChelbTerem** [alexa/alexa-apis-for-java#3] opened 2019-07-02 07:01 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request (generic to all classes)
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Calling getSystemTimeZone() from UpsServiceClass should return the current timezone or at least throw a ServiceException if there is no permission to access the timezone.

## Current Behavior

By calling 
`
RequestHelper helper = RequestHelper.forHandlerInput(this.handlerInput);
this.handlerInput.getServiceClientFactory().getUpsService().getSystemTimeZone(helper.getDeviceId())`

a NullpointerException is thrown with the current stack trace:

> Result: Failure
Exception: NullPointerException: 
Stack: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:54)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazon.ask.exception.UnhandledSkillException: Unhandled exception
	at com.amazon.ask.request.dispatcher.impl.BaseRequestDispatcher.dispatch(BaseRequestDispatcher.java:79)
	at com.amazon.ask.CustomSkill.invoke(CustomSkill.java:101)
	at com.amazon.ask.CustomSkill.invoke(CustomSkill.java:70)
	at com.amazon.ask.CustomSkill.invoke(CustomSkill.java:66)
	at de.chelbterem.MySkill.handle(MySkill.java:76)
	at de.chelbterem.Function.run(Function.java:80)
	... 16 more
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:889)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at com.amazon.ask.util.JacksonSerializer.deserialize(JacksonSerializer.java:69)
	at com.amazon.ask.model.services.BaseServiceClient.invoke(BaseServiceClient.java:109)
	at com.amazon.ask.model.services.BaseServiceClient.invoke(BaseServiceClient.java:60)
	at com.amazon.ask.model.services.ups.UpsServiceClient.getSystemTimeZone(UpsServiceClient.java:225)
	at de.chelbterem.Profile.initialize(Profile.java:86)
	at de.chelbterem.interceptors.ProfileInterceptor.process(ProfileInterceptor.java:21)
	at de.chelbterem.interceptors.ProfileInterceptor.process(ProfileInterceptor.java:13)
	at com.amazon.ask.request.dispatcher.impl.BaseRequestDispatcher.doDispatch(BaseRequestDispatcher.java:87)
	at com.amazon.ask.request.dispatcher.impl.BaseRequestDispatcher.dispatch(BaseRequestDispatcher.java:72)
	... 21 more

## Possible Solution
Calling the method should not return in an error / NullpointerException.

## Steps to Reproduce (for bugs)
`
RequestHelper helper = RequestHelper.forHandlerInput(this.handlerInput);
this.handlerInput.getServiceClientFactory().getUpsService().getSystemTimeZone(helper.getDeviceId())`

## Context
I want to greet the user of alexa with a timezone-sensitive personalized speech text. Therefore I would like to access the users timezone in order to get the right time.

Additionally, I am currently hosting my java alexa skill as an Azure function in Java.

## Your Environment
* ASK SDK Models for Java used: 2.19
* ASK SDK for Java used: 2.19
* Operating System and version: Windows 10 (Build 17763.557)
* Azure Functions Java Library used: 1.3.0

**Comment by ChelbTerem** [comment] 2019-07-02 07:03
Other functions like getProfileName(), getProfileEmail() or getProfileMobileNumber() do work and result in the actual value rather than a NullpointerException.

**Comment by breedloj** [comment] 2019-07-02 19:28
Thanks for reaching out. Can you give some more details to help us form a repro case for this issue? I am unable to reproduce this issue with a valid or invalid device ID provided, or with an invalid access token. Logging as much as possible would greatly assist us.

**Comment by ChelbTerem** [comment] 2019-07-03 05:53
Hey @breedloj, thanks for your response. I've created a minimal "not" working example which results in the NullPointerException. You can find it in my repo: https://github.com/ChelbTerem/NullpointerReproduction

**Comment by ChelbTerem** [comment] 2019-07-03 05:55
My logs show:

> Result: Failure
Exception: NullPointerException: 
Stack: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:54)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazon.ask.exception.UnhandledSkillException: Unhandled exception
	at com.amazon.ask.request.dispatcher.impl.BaseRequestDispatcher.dispatch(BaseRequestDispatcher.java:79)
	at com.amazon.ask.CustomSkill.invoke(CustomSkill.java:101)
	at com.amazon.ask.CustomSkill.invoke(CustomSkill.java:70)
	at com.amazon.ask.CustomSkill.invoke(CustomSkill.java:66)
	at com.reproduction.nullpointer.MySkill.handle(MySkill.java:25)
	at com.reproduction.nullpointer.Function.run(Function.java:40)
	... 16 more
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:889)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at com.amazon.ask.util.JacksonSerializer.deserialize(JacksonSerializer.java:69)
	at com.amazon.ask.model.services.BaseServiceClient.invoke(BaseServiceClient.java:109)
	at com.amazon.ask.model.services.BaseServiceClient.invoke(BaseServiceClient.java:60)
	at com.amazon.ask.model.services.ups.UpsServiceClient.getSystemTimeZone(UpsServiceClient.java:225)
	at com.reproduction.nullpointer.LaunchHandler.handle(LaunchHandler.java:28)
	at com.reproduction.nullpointer.LaunchHandler.handle(LaunchHandler.java:15)
	at com.amazon.ask.request.handler.adapter.impl.BaseHandlerAdapter.execute(BaseHandlerAdapter.java:42)
	at com.amazon.ask.request.dispatcher.impl.BaseRequestDispatcher.doDispatch(BaseRequestDispatcher.java:132)
	at com.amazon.ask.request.dispatcher.impl.BaseRequestDispatcher.dispatch(BaseRequestDispatcher.java:72)
	... 21 more

**Comment by ChelbTerem** [comment] 2019-07-05 05:25
@breedloj have you found the time to check out my project in order to reproduce this issue?

**Comment by breedloj** [comment] 2019-07-08 18:07
Sorry for the delay. I'm looking in to this further now. Is there any way you can log the device ID that `helper.getDeviceId()` is returning. I am wondering if you're getting a weird value back here which is causing the UPS service to send back an unexpected response that the SDK is unable to handle.

**Comment by ChelbTerem** [comment] 2019-07-09 05:26
Thanks for that @breedloj. I added a log output for the device id. It reads: 
`amzn1.ask.device.AFTMXKCJ7EWLVCTECTEP4PJVAAW7K6B63U3MQVODI4SJNCUPGLWSYLDCFGL6GYJYSTTAI5HIIERSS5DGFBRHLJBKB7WKQYW2A3WXRRQJA6PSPSANXJRBEP6XWBRUXKKPXNODRKFAMOTXNQ3Y5OJERE7AZKLR5XJR6RQ6F6B7UMCJ73SRSXUHS`

**Comment by Shreyas-vgr** [comment] 2020-07-16 17:59
Hi @ChelbTerem, are you still facing nullpointer exception on calling getSystemTimeZone() from the latest build ? 
If so, it would be great if you can create a new issue on our [ASK SDK Java repository](https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues/new) to track and get better visibility.

Closing this ticket for now.

**Closed as completed** 2020-07-16 18:03 UTC
Labels: bug
